# Generated by Django 5.1.7 on 2025-03-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_course', '0003_remove_groupcourse_rule'),
        ('group_rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='group_course.groupcourse', to_field='group_course_code'),
        ),
    ]
