# Generated by Django 5.1.3 on 2025-01-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_code', models.CharField(max_length=50, unique=True)),
                ('faculty_name', models.CharField(max_length=200)),
            ],
        ),
    ]
