# Generated by Django 5.1.3 on 2024-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('faculty_name', models.CharField(max_length=200)),
            ],
        ),
    ]
