# Generated by Django 5.1.7 on 2025-03-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learning_Outcome',
            fields=[
                ('learning_outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('learning_outcome_code', models.CharField(max_length=10)),
                ('content_vn', models.TextField()),
                ('content_en', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='courses.course', to_field='course_code')),
            ],
        ),
    ]
