# Generated by Django 5.1.7 on 2025-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10)),
                ('body', models.JSONField(blank=True, null=True)),
                ('run_time', models.DateTimeField()),
            ],
        ),
    ]
