# Generated by Django 5.1.7 on 2025-03-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtask',
            name='body',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='method',
        ),
        migrations.RemoveField(
            model_name='scheduledtask',
            name='url',
        ),
    ]
