# Generated by Django 5.1.3 on 2025-01-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnLog',
            fields=[
                ('learn_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('count_learn', models.IntegerField(default=0)),
                ('semester', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnlog', to='courses.course', to_field='course_code')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnlog', to='students.student', to_field='student_code')),
            ],
        ),
    ]
