# Generated by Django 5.1.3 on 2024-11-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('count_learner', models.IntegerField()),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credit', models.IntegerField()),
                ('is_group_c', models.BooleanField(default=False)),
                ('is_group_d', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('majors', models.ManyToManyField(related_name='courses', to='majors.major')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='courses', to='courses.course')),
            ],
        ),
    ]
