# Generated by Django 5.1.7 on 2025-03-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_course', '0001_initial'),
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('count_learner', models.IntegerField()),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credit', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='group_course.groupcourse', to_field='group_course_code')),
                ('majors', models.ManyToManyField(blank=True, related_name='courses', to='majors.major')),
                ('prerequisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_courses', to='courses.course', to_field='course_code')),
            ],
        ),
    ]
