# Generated by Django 5.1.3 on 2024-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='majors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='majors.major'),
        ),
    ]
