# Generated by Django 5.1.3 on 2024-11-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequisite_course',
            new_name='prerequisites',
        ),
    ]
