# Generated by Django 5.1.7 on 2025-03-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_code', models.CharField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_description', models.TextField()),
            ],
        ),
    ]
