# Generated by Django 5.1.7 on 2025-03-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('group_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_course_code', models.CharField(max_length=50, unique=True)),
                ('group_course_name', models.CharField(max_length=200)),
                ('total_course', models.IntegerField()),
                ('minimum_course', models.IntegerField()),
                ('alternative', models.BooleanField(default=False)),
                ('specifically', models.BooleanField(default=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('alternative_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_groups', to='group_course.groupcourse', to_field='group_course_code')),
            ],
        ),
    ]
