# Generated by Django 5.1.3 on 2025-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('group_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_course_code', models.CharField(max_length=50, unique=True)),
                ('group_course_name', models.CharField(max_length=200)),
                ('total_course', models.IntegerField()),
                ('minimum_course', models.IntegerField()),
            ],
        ),
    ]
