# Generated by Django 5.1.7 on 2025-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='rule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
