# Generated by Django 5.1.7 on 2025-03-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_course', '0003_remove_groupcourse_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcourse',
            name='alternative',
        ),
        migrations.RemoveField(
            model_name='groupcourse',
            name='alternative_group',
        ),
        migrations.RemoveField(
            model_name='groupcourse',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='groupcourse',
            name='minimum_course',
        ),
        migrations.RemoveField(
            model_name='groupcourse',
            name='specifically',
        ),
        migrations.RemoveField(
            model_name='groupcourse',
            name='total_course',
        ),
    ]
