# Generated by Django 5.1.7 on 2025-04-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_course', '0004_remove_groupcourse_alternative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
