# Generated by Django 5.1.3 on 2024-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='name',
            field=models.CharField(),
        ),
    ]
