# Generated by Django 5.1.3 on 2024-11-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_alter_syllabus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='name',
            field=models.TextField(),
        ),
    ]
