# Generated by Django 5.1.7 on 2025-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_file_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
