# Generated by Django 5.1.3 on 2025-02-25 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_file_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendlogs', to='students.student', to_field='student_code')),
            ],
        ),
    ]
