# Generated by Django 5.1.7 on 2025-03-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_needs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentneed',
            name='major',
            field=models.JSONField(),
        ),
    ]
