# Generated by Django 5.1.3 on 2025-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_needs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentneed',
            name='main_semester',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentneed',
            name='summer_semester',
            field=models.TextField(),
        ),
    ]
