# Generated by Django 5.1.3 on 2025-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_needs', '0002_alter_studentneed_main_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentneed',
            name='main_semester',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='studentneed',
            name='summer_semester',
            field=models.JSONField(),
        ),
    ]
