# Generated by Django 5.1.3 on 2025-03-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_needs', '0003_alter_studentneed_main_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentneed',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
